name: CI/CD Flask Docker (Dev)

on:
  push:
    branches: [ cicd ]   # chạy khi push lên nhánh cicd

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # Build image dev để smoke-test
      - name: Build dev image
        run: docker build -t app-dev:latest .

      # Chạy container và smoke-test HTTP /
      - name: Run container (smoke test)
        run: |
          docker run -d --name app -p 5000:5000 --env-file .env app-dev:latest
          for i in {1..20}; do
            if curl -fsS http://127.0.0.1:5000 > /dev/null; then
              echo "Smoke test OK"
              exit 0
            fi
            echo "Waiting app... ($i)"
            sleep 2
          done
          echo "Smoke test FAILED"
          docker logs app
          exit 1

      # Login trước rồi mới build-push
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push image (latest)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/orderfood-flask:latest
