name: CI/CD Flask Docker (Dev)

on:
  push:
    branches:
      - cicd

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: |
          docker build -t myflask:dev .

      - name: Run container
        run: |
          docker run -d --name myflask -p 5000:5000 --env-file .env myflask:dev
          sleep 5
          docker ps

      - name: Test app
        run: |
          curl -f http://127.0.0.1:5000 || (docker logs myflask && exit 1)

      - name: Push to DockerHub
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/orderfood-flask:latest

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
